database:
  host: 'localhost'
  port: 5432
  username: 'server'
  password: 'server'
  database: 'server'
  synchronize: false

graphql:
  playground: false
  debug: false

jwt:
  secret: 'prod_secret'
